version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: nestapi
    ports:
      - 5432:5432
networks:
  webnet:
